// Mocks generated by Mockito 5.4.6 from annotations
// in banco_douro_app/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i11;

import 'package:banco_douro_app/data/repositories/account_local_repository.dart'
    as _i9;
import 'package:banco_douro_app/models/account.dart' as _i4;
import 'package:banco_douro_app/models/account_type.dart' as _i6;
import 'package:banco_douro_app/providers/account_provider.dart' as _i12;
import 'package:banco_douro_app/providers/auth_provider.dart' as _i10;
import 'package:banco_douro_app/services/account_service.dart' as _i2;
import 'package:banco_douro_app/services/account_type_service.dart' as _i5;
import 'package:banco_douro_app/services/auth_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i2.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Account>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<bool> addAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAccount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [AccountTypeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountTypeService extends _i1.Mock
    implements _i5.AccountTypeService {
  MockAccountTypeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.AccountType>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i6.AccountType>>.value(
              <_i6.AccountType>[],
            ),
          )
          as _i3.Future<List<_i6.AccountType>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> register(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#register, [email, password]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AccountLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountLocalRepository extends _i1.Mock
    implements _i9.AccountLocalRepository {
  MockAccountLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insert(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [account]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> insertAll(List<_i4.Account>? accounts) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [accounts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Account>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i10.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AccountProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountProvider extends _i1.Mock implements _i12.AccountProvider {
  MockAccountProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Account> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i4.Account>[],
          )
          as List<_i4.Account>);

  @override
  List<_i6.AccountType> get accountTypes =>
      (super.noSuchMethod(
            Invocation.getter(#accountTypes),
            returnValue: <_i6.AccountType>[],
          )
          as List<_i6.AccountType>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingAccountTypes =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingAccountTypes),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasData =>
      (super.noSuchMethod(Invocation.getter(#hasData), returnValue: false)
          as bool);

  @override
  double get totalBalance =>
      (super.noSuchMethod(Invocation.getter(#totalBalance), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadAll() =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadAccountTypes() =>
      (super.noSuchMethod(
            Invocation.method(#loadAccountTypes, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
